
const data = [
  {
    partnerName: "billfazz",
    operator: "hehew",
    productType: "multifinance",
    product_name: "ARTHAASIA FINANCE",
    basePrice: -4325,
  },
  {
    partnerName: "billfazz",
    operator: "hihiw",
    productType: "multifinance",
    product_name: "ARTHAASIA FINANCE",
    basePrice: -4325,
  },
  {
    partnerName: "Alterra",
    operator: "FNFIF",
    productType: "multi",
    product_name: "Federal International Finance",
    basePrice: 2000,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "ARTHAASIA FINANCE",
    basePrice: -4325,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "JACCS MPM FINANCE INDONESIA MOTOR",
    basePrice: 3600,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "ANGSURAN ITC MULTI FINANCE",
    basePrice: -3825,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "BCA MULTIFINANCE ",
    basePrice: 4600,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "BUSSAN AUTO FINANCE B",
    basePrice: 5600,
  },
  {
    partnerName: "Alterra",
    operator: "MFWOKA",
    productType: "multi",
    product_name: "WOKA",
    basePrice: 2500,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "SMART FINANCE",
    basePrice: 375,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "PRO MITRA FINANCE",
    basePrice: -4325,
  },
  {
    partnerName: "Alterra",
    operator: "FNCOLUMND",
    productType: "multi",
    product_name: "Columbia Finance",
    basePrice: 2000,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "MNC FINANCE",
    basePrice: -4325,
  },
  {
    partnerName: "Alterra",
    operator: "andalan_finance",
    productType: "multi",
    product_name: "Andbursaku_api",
    basePrice: 2000,
  },
  {
    partnerName: "Alterra",
    operator: "FNFIF",
    productType: "multi",
    product_name: "Federal International Finance",
    basePrice: 2000,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "ARTHAASIA FINANCE",
    basePrice: -4325,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "JACCS MPM FINANCE INDONESIA MOTOR",
    basePrice: 3600,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "ANGSURAN ITC MULTI FINANCE",
    basePrice: -3825,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "BCA MULTIFINANCE ",
    basePrice: 4600,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "BUSSAN AUTO FINANCE B",
    basePrice: 5600,
  },
  {
    partnerName: "Alterra",
    operator: "MFWOKA",
    productType: "multi",
    product_name: "WOKA",
    basePrice: 2500,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "SMART FINANCE",
    basePrice: 375,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "PRO MITRA FINANCE",
    basePrice: -4325,
  },
  {
    partnerName: "Alterra",
    operator: "FNCOLUMND",
    productType: "multi",
    product_name: "Columbia Finance",
    basePrice: 2000,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "MNC FINANCE",
    basePrice: -4325,
  },
  {
    partnerName: "Alterra",
    operator: "andalan_finance",
    productType: "multi",
    product_name: "Andalan Finance",
    basePrice: 5000,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "INDOMOBIL FINANCE INDONESIA",
    basePrice: -5300,
  },
  {
    partnerName: "Alterra",
    operator: "mandiri_utama_finance",
    productType: "multi",
    product_name: "MUF_mobil",
    basePrice: 2000,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "BIMA FINANCE",
    basePrice: 3150,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "MANDIRI TUNAS FINANCE",
    basePrice: 1600,
  },
  {
    partnerName: "Alterra",
    operator: "mandiri_utama_finance",
    productType: "multi",
    product_name: "MUF_motor",
    basePrice: 2000,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "PRO CAR INTERNATIONAL FINANCE",
    basePrice: -4300,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "AEON CICILAN",
    basePrice: -5900,
  },
  {
    partnerName: "Alterra",
    operator: "bima_finance",
    productType: "multi",
    product_name: "Bima Finance",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "FNMAF",
    productType: "multi",
    product_name: "Mega Auto Finance",
    basePrice: 2000,
  },
  {
    partnerName: "Alterra",
    operator: "MEGAFIND",
    productType: "multi",
    product_name: "MEGA Finance",
    basePrice: 2000,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "PEMBAYARAN MANDIRI UTAMA FINANCE",
    basePrice: -4300,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "COLUMBIA FINANCE",
    basePrice: -1100,
  },
  {
    partnerName: "Alterra",
    operator: "radana_finance",
    productType: "multi",
    product_name: "Radana Finance",
    basePrice: 0,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "SUZUKI FINANCE",
    basePrice: -3225,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "TOYOTA ASTRA FINANCIAL",
    basePrice: -3225,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "JACCS MPM FINANCE INDONESIA MOBIL",
    basePrice: 7600,
  },
  {
    partnerName: "Alterra",
    operator: "Home Credit",
    productType: "multi",
    product_name: "Home Credit Open Payment",
    basePrice: 1800,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "MEGA AUTO FINANCE",
    basePrice: -1500,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "NSC FINANCE",
    basePrice: -1200,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "CLIPAN FINANCE",
    basePrice: -3325,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "BIMA FINANCE B",
    basePrice: 4000,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "WOKA FINANCE",
    basePrice: -2325,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "ARTHA PRIMA FINANCE",
    basePrice: -4300,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "BFI FINANCE",
    basePrice: -1700,
  },
  {
    partnerName: "Alterra",
    operator: "FNMEGA",
    productType: "multi",
    product_name: "Mega Central Finance",
    basePrice: 6000,
  },
  {
    partnerName: "Alterra",
    operator: "itc_finance",
    productType: "multi",
    product_name: "ITC Finance",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "mpm",
    productType: "multi",
    product_name: "JACCS MPM Finance",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "FNBAF",
    productType: "multi",
    product_name: "Bussan Auto Finance",
    basePrice: 6000,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "MEGA CENTRAL FINANCE",
    basePrice: -1500,
  },
  {
    partnerName: "Alterra",
    operator: "FNADIRAH",
    productType: "multi",
    product_name: "Adira",
    basePrice: 2000,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "RADANA FINANCE",
    basePrice: -2400,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "WOM FINANCE",
    basePrice: -1075,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "SMS FINANCE",
    basePrice: 3400,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "ADIRA FINANCE",
    basePrice: 5900,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "MPM FINANCE",
    basePrice: -2400,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "HOME CREDIT INDONESIA",
    basePrice: -1925,
  },
  {
    partnerName: "Alterra",
    operator: "Home Credit",
    productType: "multi",
    product_name: "Home Credit",
    basePrice: 0,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "FIF FINANCE",
    basePrice: 2100,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "BUSSAN AUTO FINANCE",
    basePrice: -1475,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "ANGSURAN KREDIT PLUS (FINASIA)",
    basePrice: -1550,
  },
  {
    partnerName: "Alterra",
    operator: "FNWOM",
    productType: "multi",
    product_name: "Wahana Ottomitra Multiartha",
    basePrice: 5000,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "ANGSURAN MANDALA FINANCE",
    basePrice: -4825,
  },
  {
    partnerName: "billfazz",
    productType: "multifinance",
    product_name: "MEGA FINANCE",
    basePrice: -1125,
  },
  {
    partnerName: "Alterra",
    operator: "Dompet Dhuafa",
    productType: "zakat",
    product_name: "zakat maal",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "zakat baznas",
    productType: "zakat",
    product_name: "Zakat Fitrah 40.000",
    basePrice: 500000,
  },
  {
    partnerName: "Alterra",
    operator: "aksi_cepat_tanggap",
    productType: "zakat",
    product_name: "Zakat Profesi ",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "zakat baznas",
    productType: "zakat",
    product_name: "Zakat Baznas2",
    basePrice: -1000,
  },
  {
    partnerName: "Alterra",
    operator: "zakat baznas",
    productType: "zakat",
    product_name: "Zakat Baznas1",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "aksi_cepat_tanggap",
    productType: "zakat",
    product_name: "ZakatFitrah40K",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "46",
    productType: "mobile",
    product_name: "Paket Terusan TRES 880 GB",
    basePrice: 1250000,
  },
  {
    partnerName: "Alterra",
    operator: "xl",
    productType: "mobile",
    product_name: "PRIO Medsos, Rp25rb OTC",
    basePrice: 27500,
  },
  {
    partnerName: "Alterra",
    operator: "xl",
    productType: "mobile",
    product_name: "XTRA Bicara Nelpon+Internet",
    basePrice: 30000,
  },
  {
    partnerName: "Alterra",
    operator: "xl",
    productType: "mobile",
    product_name: "Internet Umroh & Haji - 20D",
    basePrice: 249000,
  },
  {
    partnerName: "Alterra",
    operator: "indosat",
    productType: "mobile",
    product_name: "Indosat Rp 40.000",
    basePrice: 40000,
  },
  {
    partnerName: "Alterra",
    operator: "axis",
    productType: "mobile",
    product_name: "Axiata Axis BRONET 2GB",
    basePrice: 26000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Telkomsel Rp 10.000",
    basePrice: 10950,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Pulsa Internet Telkomsel Rp25.000",
    basePrice: 25000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Telkomsel Rp 5.000",
    basePrice: 6000,
  },
  {
    partnerName: "Alterra",
    operator: "xl",
    productType: "mobile",
    product_name: "XL Rp 100.000",
    basePrice: 100000,
  },
  {
    partnerName: "Alterra",
    operator: "tri",
    productType: "mobile",
    product_name: "Tri Rp 25.000",
    basePrice: 26000,
  },
  {
    partnerName: "Alterra",
    operator: "Circles_data",
    productType: "mobile",
    product_name: "Kartu Perdana + Paket Power Up 25GB Live",
    basePrice: 80000,
  },
  {
    partnerName: "Alterra",
    operator: "axis",
    productType: "mobile",
    product_name: "Axiata Axis Rp 1.000.000",
    basePrice: 1000000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Dummy Almock - Mobile",
    basePrice: 10000,
  },
  {
    partnerName: "Alterra",
    operator: "xl",
    productType: "mobile",
    product_name: "XL Rp. 50,000",
    basePrice: 50000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Telkomsel Rp 50,000",
    basePrice: 50000,
  },
  {
    partnerName: "Alterra",
    operator: "xl",
    productType: "mobile",
    product_name: "Combo XTRA M",
    basePrice: 58000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Telkomsel Data 50GB",
    basePrice: 152000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Pulsa Internet Telkomsel Rp5.000",
    basePrice: 5000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Pulsa Telkomsel Rp 500.000",
    basePrice: 501000,
  },
  {
    partnerName: "Alterra",
    operator: "xl",
    productType: "mobile",
    product_name: "Kudo XL - TSV100",
    basePrice: 101000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Telkomsel Data 50GB",
    basePrice: 502000,
  },
  {
    partnerName: "Alterra",
    operator: "axis",
    productType: "mobile",
    product_name: "Axiata Axis BRONET 3GB",
    basePrice: 39800,
  },
  {
    partnerName: "Alterra",
    operator: "smartfren",
    productType: "mobile",
    product_name: "Smartfren Rp50,000",
    basePrice: 48000,
  },
  {
    partnerName: "Alterra",
    operator: "indosat",
    productType: "mobile",
    product_name: "Indosat Rp 100.000",
    basePrice: 100000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Telkomsel 1GB",
    basePrice: 19000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Pulsa Internet Telkomsel Rp100.000",
    basePrice: 100000,
  },
  {
    partnerName: "Alterra",
    operator: "tri",
    productType: "mobile",
    product_name: "Tri Rp 5.000",
    basePrice: 5000,
  },
  {
    partnerName: "Alterra",
    operator: "tri",
    productType: "mobile",
    product_name: "Tri Rp50,000",
    basePrice: 48000,
  },
  {
    partnerName: "Alterra",
    operator: "xl",
    productType: "mobile",
    product_name: "XL Rp. 1.000.000",
    basePrice: 1000100,
  },
  {
    partnerName: "Alterra",
    operator: "tri",
    productType: "mobile",
    product_name: "Tri paket data 1gb",
    basePrice: 10000,
  },
  {
    partnerName: "Alterra",
    operator: "indosat",
    productType: "mobile",
    product_name: "Indosat Rp 50.000",
    basePrice: 49000,
  },
  {
    partnerName: "Alterra",
    operator: "Circles_data",
    productType: "mobile",
    product_name: "Paket Power Up 25GB",
    basePrice: 80000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Pulsa Telkomsel Rp 1000.000",
    basePrice: 1001000,
  },
  {
    partnerName: "Alterra",
    operator: "smartfren",
    productType: "mobile",
    product_name: "Smartfren Paket data 1GB",
    basePrice: 20000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Dummy Almock - Data",
    basePrice: 10000,
  },
  {
    partnerName: "Alterra",
    operator: "indosat",
    productType: "mobile",
    product_name: "Indosat 30GB / 30 hari",
    basePrice: 102000,
  },
  {
    partnerName: "Alterra",
    operator: "indosat",
    productType: "mobile",
    product_name: "Freedom Data Roaming 3 hari Zona 1 Asia Australia",
    basePrice: 250000,
  },
  {
    partnerName: "Alterra",
    operator: "telkomsel",
    productType: "mobile",
    product_name: "Telkomsel Rp 100,000",
    basePrice: 108000,
  },
  {
    partnerName: "Alterra",
    operator: "bpjs_ketenagakerjaan",
    productType: "bpjs_ketenagakerjaan",
    product_name: "BPJS Ketenagakerjaan 12 Bulan",
    basePrice: 320000,
  },
  {
    partnerName: "Alterra",
    operator: "bpjs_ketenagakerjaan",
    productType: "bpjs_ketenagakerjaan",
    product_name: "BPJS Ketenagakerjaan 3 Bulan",
    basePrice: 152000,
  },
  {
    partnerName: "Alterra",
    operator: "bpjs_ketenagakerjaan",
    productType: "bpjs_ketenagakerjaan",
    product_name: "BPJS Ketenagakerjaan",
    basePrice: 2500,
  },
  {
    partnerName: "Alterra",
    operator: "bpjs_ketenagakerjaan",
    productType: "bpjs_ketenagakerjaan",
    product_name: "BPJS Ketenagakerjaan 6 Bulan",
    basePrice: 220000,
  },
  {
    partnerName: "Alterra",
    operator: "bpjs_ketenagakerjaan",
    productType: "bpjs_ketenagakerjaan",
    product_name: "BPJS Ketenagakerjaan 1 Bulan",
    basePrice: 52000,
  },
  {
    "parnerName": "Alterra",
    operator: "shopee_pay",
    productType: "ewallet",
    product_name: "Saldo ShopeePay 20.000",
    basePrice: 20500,
  },
  {
    "parnerName": "Alterra",
    operator: "shopee_pay",
    productType: "ewallet",
    product_name: "Saldo ShopeePay 60.000",
    basePrice: 60500,
  },
  {
    "parnerName": "Alterra",
    operator: "gopay",
    productType: "ewallet",
    product_name: "Gopay 200k",
    basePrice: 200000,
  },
  {
    "parnerName": "Alterra",
    operator: "shopee_pay",
    productType: "ewallet",
    product_name: "Saldo ShopeePay 50.000",
    basePrice: 50500,
  },
  {
    "parnerName": "Alterra",
    operator: "linkaja",
    productType: "ewallet",
    product_name: "Linkaja 20k",
    basePrice: 20000,
  },
  {
    "parnerName": "Alterra",
    operator: "bni",
    productType: "ewallet",
    product_name: "TAPCASH BNI 10.000",
    basePrice: 11000,
  },
  {
    "parnerName": "Alterra",
    operator: "gopay",
    productType: "ewallet",
    product_name: "Gopay 0",
    basePrice: 0,
  },
  {
    "parnerName": "Alterra",
    operator: "ovo",
    productType: "ewallet",
    product_name: "OVO Rp 100.000",
    basePrice: 101000,
  },
  {
    "parnerName": "Alterra",
    operator: "shopee_pay",
    productType: "ewallet",
    product_name: "Saldo ShopeePay 30.000",
    basePrice: 30500,
  },
  {
    "parnerName": "Alterra",
    operator: "shopee_pay",
    productType: "ewallet",
    product_name: "Saldo ShopeePay 70.000",
    basePrice: 70500,
  },
  {
    "parnerName": "Alterra",
    operator: "gopay",
    productType: "ewallet",
    product_name: "Gopay 10k",
    basePrice: 12500,
  },
  {
    "parnerName": "Alterra",
    operator: "gopay",
    productType: "ewallet",
    product_name: "Gopay 100k",
    basePrice: 101000,
  },
  {
    "parnerName": "Alterra",
    operator: "e-money_mandiri",
    productType: "ewallet",
    product_name: "E-MONEY MANDIRI 50K",
    basePrice: 51000,
  },
  {
    "parnerName": "Alterra",
    operator: "shopee_pay",
    productType: "ewallet",
    product_name: "Saldo ShopeePay 300.000",
    basePrice: 300500,
  },
  {
    "parnerName": "Alterra",
    operator: "shopee_pay",
    productType: "ewallet",
    product_name: "Saldo ShopeePay 10.000",
    basePrice: 10850,
  },
  {
    "parnerName": "Alterra",
    operator: "ovo",
    productType: "ewallet",
    product_name: "OVO Rp 50.000",
    basePrice: 51000,
  },
  {
    "parnerName": "Alterra",
    operator: "shopee_pay",
    productType: "ewallet",
    product_name: "Saldo ShopeePay 200.000",
    basePrice: 200500,
  },
  {
    "parnerName": "Alterra",
    operator: "gopay",
    productType: "ewallet",
    product_name: "Gopay 50k",
    basePrice: 51000,
  },
  {
    "parnerName": "Alterra",
    operator: "dana",
    productType: "ewallet",
    product_name: "DANA 1000",
    basePrice: 10000,
  },
  {
    "parnerName": "Alterra",
    operator: "gopay",
    productType: "ewallet",
    product_name: "Gopay 1.9jt",
    basePrice: 1000000,
  },
  {
    "parnerName": "Alterra",
    operator: "e-money_mandiri",
    productType: "ewallet",
    product_name: "Emoney mandiri 100000",
    basePrice: 100000,
  },
  {
    "parnerName": "Alterra",
    operator: "ovo",
    productType: "ewallet",
    product_name: "OVO Rp 20000",
    basePrice: 20000,
  },
  {
    "parnerName": "Alterra",
    operator: "BRIZZI",
    productType: "ewallet",
    product_name: "BRIZZI 50K",
    basePrice: 51000,
  },
  {
    "parnerName": "Alterra",
    operator: "shopee_pay",
    productType: "ewallet",
    product_name: "Saldo ShopeePay 40.000",
    basePrice: 40500,
  },
  {
    "parnerName": "Alterra",
    operator: "gopay",
    productType: "ewallet",
    product_name: "Gopay 5k",
    basePrice: 5000,
  },
  {
    "parnerName": "Alterra",
    operator: "shopee_pay",
    productType: "ewallet",
    product_name: "Saldo ShopeePay 90.000",
    basePrice: 90500,
  },
  {
    "parnerName": "Alterra",
    operator: "gopay",
    productType: "ewallet",
    product_name: "Gopay 20k",
    basePrice: 21000,
  },
  {
    "parnerName": "Alterra",
    operator: "shopee_pay",
    productType: "ewallet",
    product_name: "Saldo ShopeePay 100.000",
    basePrice: 100350,
  },
  {
    "parnerName": "Alterra",
    operator: "shopee_pay",
    productType: "ewallet",
    product_name: "Saldo ShopeePay 80.000",
    basePrice: 80500,
  },
  {
    partnerName: "Alterra",
    operator: "telkom",
    productType: "telkom_postpaid",
    product_name: "Telkom Postpaid",
    basePrice: 2000,
  },
  {
    partnerName: "Alterra",
    operator: "telkom_postpaid",
    productType: "telkom_postpaid",
    product_name: "Telkom B",
    basePrice: 1,
  },
  {
    partnerName: "Alterra",
    operator: "aksi_cepat_tanggap",
    productType: "infaq",
    product_name: "IftarSahur20K",
    basePrice: 20000,
  },
  {
    partnerName: "Alterra",
    operator: "Dompet Dhuafa",
    productType: "infaq",
    product_name: "Infaq30k",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "infaq baznas",
    productType: "infaq",
    product_name: "Infaq 1 juta",
    basePrice: 1000000,
  },
  {
    partnerName: "Alterra",
    operator: "aksi_cepat_tanggap",
    productType: "infaq",
    product_name: "Takjil15K",
    basePrice: 15000,
  },
  {
    partnerName: "Alterra",
    operator: "aksi_cepat_tanggap",
    productType: "infaq",
    product_name: "Infaq100k",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "aksi_cepat_tanggap",
    productType: "infaq",
    product_name: "Takjil150K",
    basePrice: 150000,
  },
  {
    partnerName: "Alterra",
    operator: "aksi_cepat_tanggap",
    productType: "infaq",
    product_name: "Takjil90K",
    basePrice: 90000,
  },
  {
    partnerName: "Alterra",
    operator: "infaq baznas",
    productType: "infaq",
    product_name: "Infaq 150k ",
    basePrice: 150000,
  },
  {
    partnerName: "Alterra",
    operator: "infaq baznas",
    productType: "infaq",
    product_name: "Infaq 200k",
    basePrice: 200000,
  },
  {
    partnerName: "Alterra",
    operator: "infaq baznas",
    productType: "infaq",
    product_name: "Infaq 25k",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "infaq baznas",
    productType: "infaq",
    product_name: "Infaq 500k",
    basePrice: 500000,
  },
  {
    partnerName: "Alterra",
    operator: "aksi_cepat_tanggap",
    productType: "infaq",
    product_name: "IftarSahur100K",
    basePrice: 100000,
  },
  {
    partnerName: "Alterra",
    operator: "aksi_cepat_tanggap",
    productType: "infaq",
    product_name: "IftarSahur200K",
    basePrice: 200000,
  },
  {
    partnerName: "Alterra",
    operator: "infaq baznas",
    productType: "infaq",
    product_name: "Infaq 50k ",
    basePrice: 50000,
  },
  {
    partnerName: "Alterra",
    operator: "infaq baznas",
    productType: "infaq",
    product_name: "Infaq Baznas 10k",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "infaq baznas",
    productType: "infaq",
    product_name: "Infaq Baznas 500k (test-elisian)",
    basePrice: 1000,
  },
  {
    partnerName: "Alterra",
    operator: "infaq baznas",
    productType: "infaq",
    product_name: "Infaq Baznas 20k",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "zakat",
    productType: "wakaf",
    product_name: "Wakaf1000k",
    basePrice: 1000000,
  },
  {
    partnerName: "Alterra",
    operator: "zakat",
    productType: "wakaf",
    product_name: "Wakaf500k\t",
    basePrice: 500000,
  },
  {
    partnerName: "Alterra",
    operator: "zakat",
    productType: "wakaf",
    product_name: "Wakaf300k",
    basePrice: 300000,
  },
  {
    partnerName: "Alterra",
    operator: "zakat",
    productType: "wakaf",
    product_name: "Wakaf100k\t",
    basePrice: 100000,
  },
  {
    partnerName: "Alterra",
    operator: "aksi_cepat_tanggap",
    productType: "wakaf",
    product_name: "Wakaf50k",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "zakat",
    productType: "wakaf",
    product_name: "Wakaf2000k\t",
    basePrice: 2000000,
  },
  {
    partnerName: "Alterra",
    operator: "Dompet Dhuafa",
    productType: "wakaf",
    product_name: "Wakaf 200K",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "Dompet Dhuafa",
    productType: "wakaf",
    product_name: "Wakaf 500k (test-elisian)",
    basePrice: 2000,
  },
  {
    partnerName: "Alterra",
    operator: "Dompet Dhuafa",
    productType: "wakaf",
    product_name: "Wakaf 50k",
    basePrice: 51234,
  },
  {
    partnerName: "Alterra",
    operator: "aksi_cepat_tanggap",
    productType: "qurban",
    product_name: "Qurban1300k",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "Dompet Dhuafa",
    productType: "qurban",
    product_name: "Kurban domba/kambing premium (29-35 kg)",
    basePrice: 0,
  },
  {
    partnerName: "Alterra",
    operator: "infaq baznas",
    productType: "qurban",
    product_name: "Qurban Baznas",
    basePrice: 0,
  }
]
